// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleClinic.DataAccess.Models;

public partial class Clinic
{
    public int Id { get; set; }

    public string Name { get; set; }

    public TimeSpan StartWork { get; set; }

    public TimeSpan EndWork { get; set; }

    public virtual ICollection<DoctorServiceClinic> DoctorServiceClinics { get; set; } = new List<DoctorServiceClinic>();
}