// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleClinic.DataAccess.Models;

public partial class DoctorService
{
    public int Id { get; set; }

    public int? DoctorId { get; set; }

    public int? ServiceId { get; set; }

    public TimeSpan? Period { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<DoctorServiceClinic> DoctorServiceClinics { get; set; } = new List<DoctorServiceClinic>();

    public virtual Service Service { get; set; }
}