// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SimpleClinic.DataAccess.Models;

public partial class DoctorServiceClinic
{
    public int Id { get; set; }

    public int? DoctorServiceId { get; set; }

    public int? ClinicId { get; set; }

    public DateTime ServiceStartTime { get; set; }

    public DateTime ServiceEndTime { get; set; }

    public DateTime? DoctorStartWork { get; set; }

    public DateTime? DoctorEndWork { get; set; }

    public virtual Clinic Clinic { get; set; }

    public virtual DoctorService DoctorService { get; set; }

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();
}